name: PiggyShopUI
main: PiggyShopUI\Main
version: 1.0.0
api: 3.0.0
load: POSTWORLD
author: DaPigGuy
permissions:
  piggyshopui:
    default: false
    description: ""
    children:
      piggyshopui.command:
        default: op
        description: ""
        children:
          piggyshopui.command.shop:
            default: true
            description: "Use /shop"
