buy-main-menu-title: "§c§lBlackWebPE Shop-UI"
buy-category-menu-title: "{CATEGORY}"
buy-item-menu-title: "Buy {ITEM}"
buy-item-confirm-menu-title: "Confirm Transaction"
buy-categories:
  - name: "Blocks"
    image: "http://www.blocksandgold.com//media/catalog/product/cache/3/image/200x/6cffa5908a86143a54dc6ad9b8a7c38e/c/o/cobblestone_6.png"
    image-type: 1
    items:
      - menu-name: "Stone"
        id: 1
        damage: 0
        price: 5
        image: "textures/blocks/stone"
        image-type: 0
messages:
  buy-item-information: "{ITEM} cost ${PRICE} each."
  sell-item-information: "{ITEM} sell for ${PRICE} each."
  buy-item-confirmation: "Are you sure you would like to buy {COUNT}x {ITEM} for ${PRICE}."
  not-enough-money: "You do not have the required money to buy {COUNT}x {ITEM}. You are missing ${MISSING}."
  successfully-bought-item: "You have successfully bought {COUNT}x {ITEM} for ${PRICE}."
  sell-item-confirmation: "Are you sure you would like to sell {COUNT}x {ITEM} for ${PRICE}."
  missing-items: "You do not have {COUNT}x {ITEM}."
  successfully-sold-item: "You have successfully sold {COUNT}x {ITEM} for ${PRICE}."
  back-button: "Back"
